common/models/VideoView.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "{{%video_view}}".
 *
 * @property int $id
 * @property string $video_id
 * @property int|null $user_id
 * @property int|null $created_at
 *
 * @property User $user
 * @property Video $video
 */
class VideoView extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%video_view}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['video_id'], 'required'],
            [['user_id', 'created_at'], 'integer'],
            [['video_id'], 'string', 'max' => 16],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
            [['video_id'], 'exist', 'skipOnError' => true, 'targetClass' => Video::className(), 'targetAttribute' => ['video_id' => 'video_id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'video_id' => 'Video ID',
            'user_id' => 'User ID',
            'created_at' => 'Created At',
        ];
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery|\common\models\query\UserQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    /**
     * Gets query for [[Video]].
     *
     * @return \yii\db\ActiveQuery|\common\models\query\VideoQuery
     */
    public function getVideo()
    {
        return $this->hasOne(Video::className(), ['video_id' => 'video_id']);
    }

    /**
     * {@inheritdoc}
     * @return \common\models\query\VideoViewQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\VideoViewQuery(get_called_class());
    }
}

backend/controllers/CommentController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Comment;
use backend\models\CommentSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CommentController implements the CRUD actions for Comment model.
 */
class CommentController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@']
                    ]
                ]
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Comment models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CommentSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, Yii::$app->user->id);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Comment model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Comment model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Comment();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Comment model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Comment model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Comment model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Comment the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Comment::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

frontend/controllers/CommentController.php
<?php
/**
 * User: TheCodeholic
 * Date: 11/12/2020
 * Time: 8:58 AM
 */

namespace frontend\controllers;


use common\models\Comment;
use common\models\User;
use yii\filters\AccessControl;
use yii\filters\ContentNegotiator;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;

/**
 * Class CommentController
 *
 * @author  Zura Sekhniashvili <zurasekhniashvili@gmail.com>
 * @package frontend\controllers
 */
class CommentController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['create'],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@']
                    ]
                ]
            ],
            'content' => [
                'class' => ContentNegotiator::class,
                'only' => ['create', 'update', 'delete', 'reply', 'by-parent', 'pin'],
                'formats' => [
                    'application/json' => Response::FORMAT_JSON
                ]
            ],
            'verb' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST']
                ]
            ]
        ];
    }

    public function actionCreate($id)
    {
        $comment = new Comment();
        $comment->video_id = $id;
        if ($comment->load(\Yii::$app->request->post(), '') && $comment->save()) {
            return [
                'success' => true,
                'comment' => $this->renderPartial('@frontend/views/video/_comment_item', [
                    'model' => $comment,
                ])
            ];
        }

        return [
            'success' => false,
            'errors' => $comment->errors
        ];
    }

    public function actionDelete($id)
    {
        $comment = $this->findModel($id);
        if ($comment->belongsTo(\Yii::$app->user->id) || $comment->video->belongsTo(\Yii::$app->user->id)) {
            $comment->delete();

            return ['success' => true];
        }
        throw new ForbiddenHttpException();
    }

    public function actionUpdate($id)
    {
        $comment = $this->findModel($id);
        if ($comment->belongsTo(\Yii::$app->user->id)) {
            $commentText = \Yii::$app->request->post('comment');
            $comment->comment = $commentText;
            if ($comment->save()) {
                return [
                    'success' => true,
                    'comment' => $this->renderPartial('@frontend/views/video/_comment_item', [
                        'model' => $comment,
                    ])
                ];
            }

            return [
                'success' => false,
                'errors' => $comment->errors
            ];
        }
        throw new ForbiddenHttpException();
    }

    public function actionReply()
    {
        $parentId = \Yii::$app->request->post('parent_id');
        $parentComment = $this->findModel($parentId);

        $commentText = \Yii::$app->request->post('comment');
        $mentionUsername = \Yii::$app->request->post('mention');
        if (strpos($commentText, '@' . $mentionUsername) !== 0) {
            $mentionUsername = null;
        } else {
            $commentText = trim(str_replace('@' . $mentionUsername, '', $commentText));
        }

        if ($mentionUsername) {
            $mentionUser = User::findByUsername($mentionUsername);
            if (!$mentionUser) {
                $mentionUsername = null;
            } else {
                $currentUser = \Yii::$app->user->identity;
                \Yii::$app->mailer->compose([
                    'html' => 'mention-html', 'text' => 'mention-text'
                ], [
                    'comment' => $commentText,
                    'channel' => $mentionUser,
                    'user' => $currentUser
                ])
                    ->setFrom(\Yii::$app->params['senderEmail'])
                    ->setTo($mentionUser->email)
                    ->setSubject('User '.$currentUser->username.' mention you in a comment')
                    ->send();
            }
        }

        $comment = new Comment();
        $comment->comment = $commentText;
        $comment->mention = $mentionUsername;
        $comment->video_id = $parentComment->video_id;

        if ($parentComment->parent_id) {
            $comment->parent_id = $parentComment->parent_id;
        } else {
            $comment->parent_id = $parentId;
        }


        if ($comment->save()) {
            return [
                'success' => true,
                'comment' => $this->renderPartial('@frontend/views/video/_comment_item', [
                    'model' => $comment,
                ])
            ];
        }

        return [
            'success' => false,
            'errors' => $comment->errors
        ];
    }

    public function actionByParent($id)
    {
        $parentComment = $this->findModel($id);

        $finalContent = "";
        foreach ($parentComment->comments as $comment) {
            $finalContent .= $this->renderPartial('@frontend/views/video/_comment_item', [
                'model' => $comment,
            ]);
        }

        return [
            'success' => true,
            'comments' => $finalContent
        ];
    }

    public function actionPin($id)
    {
        $comment = $this->findModel($id);
        if ($comment->video->belongsTo(\Yii::$app->user->id)) {
            if ($comment->pinned) {
                $comment->pinned = 0;
            } else {
                Comment::updateAll(['pinned' => 0], ['video_id' => $comment->video]);
                $comment->pinned = 1;
            }
            if ($comment->save()) {
                return [
                    'success' => true,
                    'comment' => $this->renderPartial('@frontend/views/video/_comment_item', [
                        'model' => $comment,
                    ])
                ];
            }

            return [
                'success' => false,
                'errors' => $comment->errors
            ];
        }

        throw new ForbiddenHttpException();
    }

    protected function findModel($id)
    {
        $comment = Comment::findOne($id);
        if (!$comment) {
            throw new NotFoundHttpException;
        }

        return $comment;
    }
}

frontend/controllers/VideoController.php
<?php
/**
 * User: TheCodeholic
 * Date: 4/17/2020
 * Time: 11:56 AM
 */

namespace frontend\controllers;


use common\models\Comment;
use common\models\Video;
use common\models\VideoLike;
use common\models\VideoView;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * Class VideoController
 *
 * @author  Zura Sekhniashvili <zurasekhniashvili@gmail.com>
 * @package frontend\controllers
 */
class VideoController extends Controller
{

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['like', 'dislike', 'history'],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@']
                    ]
                ]
            ],
            'verb' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'like' => ['post'],
                    'dislike' => ['post'],
                ]
            ]
        ];
    }

    public function actionIndex()
    {
        $this->layout = 'main';
        $dataProvider = new ActiveDataProvider([
            'query' => Video::find()->with('createdBy')->published()->latest(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider
        ]);
    }

    public function actionView($id)
    {
        $this->layout = 'auth';
        $video = $this->findVideo($id);

        $videoView = new VideoView();
        $videoView->video_id = $id;
        $videoView->user_id = \Yii::$app->user->id;
        $videoView->created_at = time();
        $videoView->save();

        $similarVideos = Video::find()
            ->published()
            ->byKeyword($video->title)
            ->andWhere(['NOT', ['video_id' => $id]])
            ->limit(10)
            ->all();

        $comments = $video
            ->getComments()
            ->with(['createdBy'])
            ->parent()
            ->latest()
            ->all();

        return $this->render('view', [
            'model' => $video,
            'comments' => $comments,
            'similarVideos' => $similarVideos
        ]);
    }

    public function actionLike($id)
    {
        $video = $this->findVideo($id);
        $userId = \Yii::$app->user->id;

        $videoLikeDislike = VideoLike::find()
            ->userIdVideoId($userId, $id)
            ->one();
        if (!$videoLikeDislike) {
            $this->saveLikeDislike($id, $userId, VideoLike::TYPE_LIKE);
        } else if ($videoLikeDislike->type == VideoLike::TYPE_LIKE) {
            $videoLikeDislike->delete();
        } else {
            $videoLikeDislike->delete();
            $this->saveLikeDislike($id, $userId, VideoLike::TYPE_LIKE);
        }

        return $this->renderAjax('_buttons', [
            'model' => $video
        ]);
    }

    public function actionDislike($id)
    {
        $video = $this->findVideo($id);
        $userId = \Yii::$app->user->id;

        $videoLikeDislike = VideoLike::find()
            ->userIdVideoId($userId, $id)
            ->one();
        if (!$videoLikeDislike) {
            $this->saveLikeDislike($id, $userId, VideoLike::TYPE_DISLIKE);
        } else if ($videoLikeDislike->type == VideoLike::TYPE_DISLIKE) {
            $videoLikeDislike->delete();
        } else {
            $videoLikeDislike->delete();
            $this->saveLikeDislike($id, $userId, VideoLike::TYPE_DISLIKE);
        }

        return $this->renderAjax('_buttons', [
            'model' => $video
        ]);
    }

    public function actionSearch($keyword)
    {
        $this->layout = 'main';
        $query = Video::find()
            ->with('createdBy')
            ->published()
            ->latest();
        if ($keyword) {
            $query->byKeyword($keyword);
        }
        $dataProvider = new ActiveDataProvider([
            'query' => $query
        ]);

        return $this->render('search', [
            'dataProvider' => $dataProvider
        ]);
    }

    public function actionHistory()
    {
        $this->layout = 'main';
        $query = Video::find()
            ->alias('v')
            ->innerJoin("(SELECT video_id, MAX(created_at) as max_date FROM video_view
                    WHERE user_id = :userId
                    GROUP BY video_id) vv", 'vv.video_id = v.video_id', [
                'userId' => \Yii::$app->user->id
            ])
            ->orderBy("vv.max_date DESC");

        $dataProvider = new ActiveDataProvider([
            'query' => $query
        ]);

        return $this->render('history', [
            'dataProvider' => $dataProvider
        ]);
    }

    protected function findVideo($id)
    {
        $video = Video::findOne($id);
        if (!$video) {
            throw new NotFoundHttpException("Video does not exit");
        }

        return $video;
    }

    protected function saveLikeDislike($videoId, $userId, $type)
    {
        $videoLikeDislike = new VideoLike();
        $videoLikeDislike->video_id = $videoId;
        $videoLikeDislike->user_id = $userId;
        $videoLikeDislike->type = $type;
        $videoLikeDislike->created_at = time();
        $videoLikeDislike->save();
    }
}

frontend/views/video/_buttons.php
<?php
/**
 * User: TheCodeholic
 * Date: 4/18/2020
 * Time: 9:23 AM
 */
/** @var $model \common\models\Video */

use yii\helpers\Url;

?>
<a href="<?php echo Url::to(['/video/like', 'id' => $model->video_id]) ?>"
   class="btn btn-sm <?php echo $model->isLikedBy(Yii::$app->user->id) ? 'btn-outline-primary': 'btn-outline-secondary' ?>"
   data-method="post" data-pjax="1">
    <i class="fas fa-thumbs-up"></i> <?php echo $model->getLikes()->count() ?>
</a>
<a href="<?php echo Url::to(['/video/dislike', 'id' => $model->video_id]) ?>"
   class="btn btn-sm <?php echo $model->isDislikedBy(Yii::$app->user->id) ? 'btn-outline-primary': 'btn-outline-secondary' ?>"
   data-method="post" data-pjax="1">
    <i class="fas fa-thumbs-down"></i> <?php echo $model->getDislikes()->count() ?>
</a>

frontend/views/video/_comment_item.php
<?php
/**
 * User: TheCodeholic
 * Date: 11/12/2020
 * Time: 9:19 AM
 */

/** @var $model \common\models\Comment */

$subCommentCount = $model->getComments()->count();
?>

<div class="comment-item <?php echo $model->pinned ? 'pinned-comment' : ''?>" data-parent-id="<?php echo $model->parent_id ?>" data-id="<?php echo $model->id ?>">
    <div class="media media-comment">
        <img class="mr-3 comment-avatar" src="/img/avatar.svg" alt="">
        <div class="media-body">
            <h6 class="mt-0">
                <?php if ($model->pinned): ?>
                    <div class="pinned-text text-muted mb-1">
                        <i class="fas fa-thumbtack"></i> Pinned comment
                    </div>
                <?php endif; ?>
                <?php echo \common\helpers\Html::channelLink($model->createdBy) ?>
                <small class="text-muted">
                    <?php echo Yii::$app->formatter->asRelativeTime($model->created_at) ?>
                    <?php if ($model->created_at !== $model->updated_at): ?>
                        (edited)
                    <?php endif; ?>
                </small>
            </h6>
            <div class="comment-text">
                <div class="text-wrapper">
                    <?php if ($model->mention): ?>
                        <span class="badge bg-info"><?php echo '@'.$model->mention ?></span>
                    <?php endif; ?>
                    <?php echo $model->comment ?>
                </div>

                <div class="bottom-actions my-2">
                    <button data-action="<?php echo \yii\helpers\Url::to(['/comment/reply']) ?>"
                            class="btn btn-sm btn-light btn-reply">
                        REPLY
                    </button>
                </div>
                <div class="reply-section">

                </div>
                <?php if ($subCommentCount): ?>
                    <div class="mb-2">
                        <a href="<?php echo \yii\helpers\Url::to(['/comment/by-parent', 'id' => $model->id]) ?>"
                           class="view-sub-comments">View <?php echo $subCommentCount ?> replies</a>
                    </div>
                <?php endif; ?>
                <div class="sub-comments">

                </div>
            </div>
            <?php if ($model->belongsTo(Yii::$app->user->id) || $model->video->belongsTo(Yii::$app->user->id)): ?>
                <div class="dropdown comment-actions">
                    <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton"
                            data-toggle="dropdown">
                        <i class="fas fa-ellipsis-v"></i>
                    </button>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                        <?php if (!$model->parent_id && $model->video->belongsTo(Yii::$app->user->id)): ?>
                            <a class="dropdown-item item-pin-comment"
                               data-pinned="<?php echo $model->pinned ?>"
                               href="<?php echo \yii\helpers\Url::to(['/comment/pin', 'id' => $model->id]) ?>">
                                <i class="fas fa-thumbtack"></i>
                                <?php if ($model->pinned): ?>
                                    Unpin
                                <?php else: ?>
                                    Pin
                                <?php endif; ?>
                            </a>
                        <?php endif; ?>

                        <?php if ($model->belongsTo(Yii::$app->user->id)): ?>
                            <a class="dropdown-item item-edit-comment" href="#">
                                <i class="fas fa-edit"></i>
                                Edit
                            </a>
                        <?php endif; ?>
                        <a class="dropdown-item item-delete-comment"
                           href="<?php echo \yii\helpers\Url::to(['/comment/delete', 'id' => $model->id]) ?>">
                            <i class="fas fa-trash"></i>
                            Delete
                        </a>
                    </div>
                </div>
            <?php endif; ?>
        </div>
    </div>
    <div class="media media-input">
        <img class="mr-3 comment-avatar" src="/img/avatar.svg" alt="">
        <div class="media-body">
            <form class="comment-edit-section" method="post"
                  action="<?php echo \yii\helpers\Url::to(['/comment/update', 'id' => $model->id]) ?>">
            <textarea rows="1"
                      class="form-control"
                      name="comment"
                      placeholder="Add a public comment"></textarea>
                <div class="action-buttons text-right mt-2">
                    <button type="button" class="btn btn-light btn-cancel">Cancel</button>
                    <button class="btn btn-primary btn-save">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

frontend/views/video/_video_item.php
<?php
/**
 * User: TheCodeholic
 * Date: 4/17/2020
 * Time: 12:00 PM
 */

use yii\helpers\Url;

/** @var $model \common\models\Video */
?>

<div class="card m-3" style="width: 14rem;">
    <a href="<?php echo Url::to(['/video/view', 'id' => $model->video_id]) ?>">
        <div class="embed-responsive embed-responsive-16by9">
            <video class="embed-responsive-item"
                   poster="<?php echo $model->getThumbnailLink() ?>"
                   src="<?php echo $model->getVideoLink() ?>"></video>
        </div>
    </a>
    <div class="card-bod p-2">
        <h6 class="card-title m-0"><?php echo $model->title ?></h6>
        <p class="text-muted card-text m-0">
            <?php echo \common\helpers\Html::channelLink($model->createdBy) ?>
        </p>
        <p class="text-muted card-text m-0">
            <?php echo $model->getViews()->count() ?> views .
            <?php echo Yii::$app->formatter->asRelativeTime($model->created_at) ?>
        </p>
    </div>
</div>

frontend/views/video/history.php
<?php
/**
 * User: TheCodeholic
 * Date: 4/17/2020
 * Time: 11:56 AM
 */
/** @var $dataProvider \yii\data\ActiveDataProvider */

$this->title = 'My Visited videos | '. Yii::$app->name;
?>
<h1>My Visited videos</h1>
<?php echo \yii\widgets\ListView::widget([
    'dataProvider' => $dataProvider,
    'itemView' => '_video_item',
    'layout' => '<div class="d-flex flex-wrap">{items}</div>{pager}',
    'itemOptions' => [
        'tag' => false
    ]
]) ?>

frontend/views/video/index.php
<?php
/**
 * User: TheCodeholic
 * Date: 4/17/2020
 * Time: 11:56 AM
 */
/** @var $this \yii\web\View */
/** @var $dataProvider \yii\data\ActiveDataProvider */

$this->title = 'Popular videos | '. Yii::$app->name;
?>

<?php echo \yii\widgets\ListView::widget([
    'dataProvider' => $dataProvider,
    'pager' => [
        'class' => \yii\bootstrap4\LinkPager::class,
    ],
    'itemView' => '_video_item',
    'layout' => '<div class="d-flex flex-wrap">{items}</div>{pager}',
    'itemOptions' => [
        'tag' => false
    ]
]) ?>

frontend/views/video/search.php
<?php
/**
 * User: TheCodeholic
 * Date: 4/17/2020
 * Time: 11:56 AM
 */
/** @var $dataProvider \yii\data\ActiveDataProvider */

$this->title = 'Search videos | '. Yii::$app->name;
?>
<h1>Found videos</h1>
<?php echo \yii\widgets\ListView::widget([
    'dataProvider' => $dataProvider,
    'itemView' => '_video_item',
    'layout' => '<div class="d-flex flex-wrap">{items}</div>{pager}',
    'itemOptions' => [
        'tag' => false
    ]
]) ?>

frontend/views/video/view.php
<?php
/**
 * User: TheCodeholic
 * Date: 4/18/2020
 * Time: 8:48 AM
 */

use yii\helpers\Html;
use yii\helpers\Url;

/** @var $this \yii\web\View */
/** @var $model \common\models\Video */
/** @var $similarVideos \common\models\Video[] */
/** @var $comments \common\models\Comment[] */

$this->title = $model->title . ' | ' . Yii::$app->name;
?>
<div class="row">
    <div class="col-sm-8">
        <div class="embed-responsive embed-responsive-16by9">
            <video class="embed-responsive-item"
                   poster="<?php echo $model->getThumbnailLink() ?>"
                   src="<?php echo $model->getVideoLink() ?>"
                   controls></video>
        </div>
        <h6 class="mt-2"><?php echo $model->title ?></h6>
        <div class="d-flex justify-content-between align-items-center">
            <div>
                <?php echo $model->getViews()->count() ?> views •
                <?php echo Yii::$app->formatter->asDate($model->created_at) ?>
            </div>
            <div>
                <?php \yii\widgets\Pjax::begin() ?>
                <?php echo $this->render('_buttons', [
                    'model' => $model
                ]) ?>
                <?php \yii\widgets\Pjax::end() ?>
            </div>
        </div>
        <div>
            <p>
                <?php echo \common\helpers\Html::channelLink($model->createdBy) ?>
            </p>
            <?php echo Html::encode($model->description) ?>
        </div>
        <div class="comments mt-5">
            <h4 class="mb-3"> <span id="comment-count"><?php echo $model->getComments()->count() ?></span> Comments</h4>
            <div class="create-comment mb-4">
                <div class="media">
                    <img class="mr-3 comment-avatar" src="/img/avatar.svg" alt="">
                    <div class="media-body">
                        <form class="create-comment-form" method="post"
                              action="<?php echo Url::to(['/comment/create', 'id' => $model->video_id]) ?>">
                            <input type="hidden" name="video_id" value="<?php echo $model->video_id ?>">
                            <textarea rows="1"
                                      class="form-control comment-input"
                                      name="comment"
                                      placeholder="Add a public comment"></textarea>
                            <div class="action-buttons text-right mt-2">
                                <button type="button" class="btn btn-light btn-cancel">Cancel</button>
                                <button class="btn btn-primary btn-save">Comment</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div id="comments-wrapper" class="comments-wrapper">
                <?php foreach ($comments as $comment) {
                    echo $this->render('_comment_item', [
                        'model' => $comment,
                    ]);
                } ?>
            </div>
        </div>
    </div>
    <div class="col-sm-4">
        <?php foreach ($similarVideos as $similarVideo): ?>
            <div class="media mb-3">
                <a href="<?php echo Url::to(['/video/view', 'id' => $similarVideo->video_id]) ?>">
                    <div class="embed-responsive embed-responsive-16by9 mr-2"
                         style="width: 120px">
                        <video class="embed-responsive-item"
                               poster="<?php echo $similarVideo->getThumbnailLink() ?>"
                               src="<?php echo $similarVideo->getVideoLink() ?>"></video>
                    </div>
                </a>
                <div class="media-body">
                    <h6 class="m-0"><?php echo $similarVideo->title ?></h6>
                    <div class="text-muted">
                        <p class="m-0">
                            <?php echo \common\helpers\Html::channelLink($similarVideo->createdBy) ?>
                        </p>
                        <small>
                            <?php echo $similarVideo->getViews()->count() ?> views •
                            <?php echo Yii::$app->formatter->asRelativeTime($similarVideo->created_at) ?>
                        </small>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>